### PR TITLE
Advanced checkpointing

### PR DESCRIPTION
**Pull request by astanziola**
This PR introduces new checkpointing method for time domein simulations, in particoular the Treeverse and Divide&Conquer methods. Hopefully this will ease memory requirements for backpropagating large simulations.
Please note that this will only be effective when using sparse sensors, as otherwise all fields for all timesteps need to be kept in memory anyway.

Literature:
- D&Q: https://arxiv.org/abs/1708.06799
- Treeverse (Revolve): https://dl.acm.org/doi/10.1145/347837.347846
- Recursive checkpointing is based on this sketched implementation: https://github.com/google/jax/issues/4285#issuecomment-696281412
- Discussion about checkpointing on scan function in the JAX repo: https://github.com/google/jax/issues/2139

ToDo list:
- [x] Initial implementation of checkpointed scan methods
- [x] Use new scan functions in the acoustic solver

### CODE REVIEW

**Comment by astanziola** [comment]
This also solves #127

**Comment by astanziola** [comment]
This needs more testing, but merging it since it provides several bug fixes, especially given the new breaking changes coming from jax 0.4.
Now we finally have proper depdency version locks to prevent such issues in the future. I know, I should have done it earlier.

**Comment by patrick-kidger** [comment]
I think the implementations here suffer from exploding compile times, due to tracing the step function multiple times, and it doesn't look like the treeverse implementation is actually recursively nesting itself?

Anyway: I saw this thread referenced in the above links, so if it helps anyone here, [Equinox](http://github.com/patrick-kidger/equinox) now supports while loops with recursive checkpointing (and efficient compile times). See also [this comment](https://github.com/google/jax/issues/2139#issuecomment-1439334364).

**Comment by astanziola** [comment]
Hi @patrick-kidger sorry for missing this, it was a time of "transition" for me when you sent it :) Thanks a lot for point this out.

I have actually made a branch that uses `diffrax` directly for replacing the semi-implicit euler step and works amazingly, so I can probably leverage all your hard work to do this instead of relying on my crappy implementation!

**Pull request merged**
